version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: hr-v2-mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=db_hr_v2
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3306"
    volumes:
      - hr_v2_db_data:/var/lib/mysql

volumes:
  hr_v2_db_data:
